# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-20 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiRestfulUsers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='Beuler', max_length=255),
        ),
    ]
